/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/apps/brussel/RL8/zen4/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Traceback (most recent call last):
  File "/vscmnt/brussel_pixiu_data/_data_brussel/vo/000/bvo00012/vsc11137/source2suffering/main.py", line 515, in <module>
    grid_area,
  File "/vscmnt/brussel_pixiu_data/_data_brussel/vo/000/bvo00012/vsc11137/source2suffering/gridscale.py", line 2373, in load_gdp_deprivation
    with open(data_dir+'{}/gdp_deprivation/gdp_dataset.pkl'.format(flags['version']), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/brussel/vo/000/bvo00012/vsc11137/source2suffering/data/pickles_v3/gdp_deprivation/gdp_dataset.pkl'
